### ISSUE TITLE
Problems with FastAsyncWorldEdit

### ISSUE THREAD

**Issue by thaumiel9** [Foulest/Vault#7]
Server: purpur-1.20.6-2232.jar
Vault: Vault-2.3.9.jar
FastAsyncWorldEdit: FastAsyncWorldEdit-Bukkit-2.10.0.jar

Everything works fine with MilkBowl's vault 1.7.3, but it has issues with Foulest's vault 2.3.9.

[log.log](https://github.com/user-attachments/files/15831181/log.log)

**Comment by Foulest** [comment]
Check the latest release. It should be fixed. @thaumiel9

**Comment by thaumiel9** [comment]
It has been fixed, thank you very much! @Foulest
