### ISSUE TITLE
TownyChat Error

### ISSUE THREAD

**Issue by Houdeeny** [Foulest/Vault#8]
The chat works fine with the normal Vault plugin, but not when using this fork.

Server Version: `Purpur 1.20.6-2232-f1c87e4 (MC: 1.20.6)`
Vault Version: `Vault-2.4.1`
TownyChat Version: `TownyChat-0.115`

Logs: https://mclo.gs/Hxx8uQO

**Comment by Foulest** [comment]
Fixed in the latest version.
